name: ci

on: [push, workflow_dispatch]

defaults:
  run:
    shell: bash

jobs:
  test-without-downloads:
    runs-on: ubuntu-latest
    strategy:
    matrix:
      container-os: ["debian:12", "ubuntu:22.04"]
    container: public.ecr.aws/docker/library/${{ matrix.container-os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: apt-get update && apt-get install -y wget

      - name: Run install script without downloads
        run: ./install.sh

      - name: Test tweaks
        run: |
          shopt -s expand_aliases
          source ~/.bash_aliases
          ll
          grep -E "^set constantshow" ~/.nanorc
          grep -E "history-search-backward" ~/.inputrc

  test-with-downloads:
    runs-on: ubuntu-latest
    strategy:
    matrix:
      container-os: ["debian:12", "ubuntu:22.04"]
    container: public.ecr.aws/docker/library/${{ matrix.container-os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: apt-get update && apt-get install -y wget

      - name: Run install script with downloads
        run:  |
          rm \
            ~/.bash_aliases files/.bash_aliases \
            ~/.nanorc files/.nanorc \
            ~/.inputrc files/.inputrc
          ./install.sh

      - name: Test tweaks
        run: |
          shopt -s expand_aliases
          source ~/.bash_aliases
          ll
          grep -E "^set constantshow" ~/.nanorc
          grep -E "history-search-backward" ~/.inputrc
