name: CI
run-name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container-os: ["debian:12", "ubuntu:22.04"]
        with-downloads: ["with-downloads", "no-downloads"]
    container: public.ecr.aws/docker/library/${{ matrix.container-os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: apt-get update && apt-get install -y wget git

      - name: Delete Files Directory
        if: ${{ matrix.with-downloads == 'with-downloads' }}
        run: rm -r files

      - name: Run Install Script
        run: ./install.sh

      - name: Test Tweaks
        run: |
          shopt -s expand_aliases
          [ $? -ne 0 ] && echo "Checkpoint 1 error" && exit 1
          source ~/.bash_aliases
          [ $? -ne 0 ] && echo "Checkpoint 2 error" && exit 1
          grep -E "export PS1.+parse_git_branch" ~/.bashrc
          [ $? -ne 0 ] && echo "Checkpoint 3 error" && exit 1
          if [[ -f ~/.profile ]]; then source ~/.profile; fi
          [ $? -ne 0 ] && echo "Checkpoint 4 error" && exit 1
          ll
          [ $? -ne 0 ] && echo "Checkpoint 5 error" && exit 1
          grep -E "^set constantshow" ~/.nanorc
          [ $? -ne 0 ] && echo "Checkpoint 6 error" && exit 1
          grep -E "history-search-backward" ~/.inputrc
          [ $? -ne 0 ] && echo "Checkpoint 7 error" && exit 1
          echo ${PATH} | grep "/usr/local/sbin" 
          [ $? -ne 0 ] && echo "Checkpoint 8 error" && exit 1
