name: ci

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container-os: ["debian:12", "ubuntu:22.04"]
    container: public.ecr.aws/docker/library/${{ matrix.container-os }}
    steps:
      - uses: actions/checkout@v4

      #- name: Source install script
      #  run: . install.sh

      - name: Test aliases
        run: |
          pwd
          ls -al
          ls -al /github/home
          ls -al /__w/linux-qol-tweaks/linux-qol-tweaks
          ls ~
          ll ~
