name: ci

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container-os: ["debian:12", "ubuntu:22.04"]
    container: public.ecr.aws/docker/library/${{ matrix.container-os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Source install script
        run: . install.sh
        # run: |
        #   ls -l install.sh
        #   echo $SHELL
        #   echo $0
        #   echo $PATH
        #   cat /etc/passwd | grep root
        #   #help source
        #   #source install.sh

      - name: Test aliases
        run: |
          ls
          ll
